<div class="jumbotron">
	<div class="container">
		<h1>Gintender's Database</h1>
	</div>
</div>

<div class="container">
		
<table align="center">
	<tr>
	<td style="width: 500px;">
		  <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('gin/query'));
        $form->setAttribute('class', 'ajax');
        $form->setAttribute('method', 'post');
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
			<div class="form-group"  style="display: inline;">
				<?php
				$element = $form->get('Juniper');
				echo $this->formLabel($element);
				echo $this->formSelect($element);
				echo $this->formElementErrors($element);
				?>
			</div>
		
		<div data-role="collapsible">
			<h4>Advanced</h4>
			<div class="form-group"  style="display: inline; float:left;">
				<?php
				$element = $form->get('Citrus');
				echo $this->formLabel($element);
				echo $this->formSelect($element);
				echo $this->formElementErrors($element);
				?>
			</div>
	
		
			<div class="form-group"  style="display: inline; float:left;">
            <?php
            $element = $form->get('Spice');
            echo $this->formLabel($element);
            echo $this->formSelect($element);
            echo $this->formElementErrors($element);
            ?>
			</div>
		
			<div class="form-group"  style="display: inline; float: left;">
            <?php
            $element = $form->get('Herbal');
            echo $this->formLabel($element);
            echo $this->formSelect($element);
            echo $this->formElementErrors($element);
            ?>
			</div>
		
			<div class="form-group"  style="display: inline; float: left;">
            <?php
            $element = $form->get('Floral');
            echo $this->formLabel($element);
            echo $this->formSelect($element);
            echo $this->formElementErrors($element);
            ?>
			</div>
		</div>
	 <div class="form-group">
			<?php
            $element = $form->get('submit');
            echo $this->formSubmit($element);
            echo $this->formElementErrors($element);
            ?>
    </div>
	
			<?php echo $this->form()->closeTag(); ?>
	</td>
	</tr>	
	</table>
	
	
		

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
	<?php if (!isset($_POST['Citrus'], $_POST['Spice'], $_POST['Herbal'], $_POST['Floral'])) {
				$message = "Pick your ingredient levels";
				echo $message;
				}
	?>

			<div class="table-responsive">
				<table class="table table-hover table-condensed table-striped" id="gindata" name="gindata" align="center">

				<!--This is were query results show up -->

				</table>
			</div>
		
		</div>
	</div>
	
	
<div id="myModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					
				</div>
				<div id="gin_details" class="modal-body">
				
				</div>
				<div class="modal-footer" style="clear: both;">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal --> 

	
</div>

