<div class="jumbotron">
	<div class="container">
		<h1>Gintender's Database</h1>
	</div>
</div>

<div class="container">
	<div class="row">
	
		<table align="center">
			
			<td>
			
			<form action="includes/profile_query.php" class="ajax" method="POST">
				<input type="text" name="Search">
				<input type="submit" value="Search">
			</form>	
				
			</td>	
				
			</tr>
		
		</table>
		
		<table align="center">
			<tr>
			<td>
			
			<form action="includes/profile_query.php" class="ajax" method="POST">
				Juniper: <select name="Juniper" >
				<option value="1">Light</option>
				<option value="2">Medium</option>
				<option value="3">Heavy</option>
				</select>
				<input type="submit" value="Submit">
			</form>	
				
			</td>	
				
			</tr>
		
		</table>
		

	<table align="center">
		<tr>
			<td>
	<form action="includes/profile_query.php" class="ajax" method="post" >
				Citrus: <select name="Citrus" >
				
				<option value="0">Light</option>
				<option value="1">Medium</option>
				<option value="2">Heavy</option>
				<option value="3">Extra Heavy</option>
				</select>
				Spice: <select name="Spice" >
				
				<option value="0">Light</option>
				<option value="1">Medium</option>
				<option value="2">Heavy</option>
				<option value="3">Extra Heavy</option>
				</select>
				Herbal: <select name="Herbal" >
				
				<option value="0">Light</option>
				<option value="1">Medium</option>
				<option value="2">Heavy</option>
				<option value="3">Extra Heavy</option>
				</select>
				Floral: <select name="Floral" >
				
				<option value="0">Light</option>
				<option value="1">Medium</option>
				<option value="2">Heavy</option>
				<option value="3">Extra Heavy</option>
				</select>

				<input type="submit" value="Submit">
				</form>
	
			</td>
			

		</tr>
	</table>
	
	</div>
		

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
	<?php if (!isset($_POST['Citrus'], $_POST['Spice'], $_POST['Herbal'], $_POST['Floral'])) {
				$message = "Pick your ingredient levels";
				echo $message;
				}
	?>

			<div class="table-responsive">
				<table class="table table-hover table-condensed table-striped" id="gindata" name="gindata" align="center">

				<!--This is were query results show up -->

				</table>
			</div>
		
		</div>
	</div>
	
	
<div id="myModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					
				</div>
				<div id="gin_details" class="modal-body">
				
				</div>
				<div class="modal-footer" style="clear: both;">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal --> 

	
</div>

<script src="js/main.js"></script> 
